# Generated by Django 4.1.7 on 2023-03-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='novedad',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
