# Generated by Django 4.1.7 on 2023-03-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0002_producto_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank='', choices=[('escolar', 'Escolar'), ('papel', 'Papel'), ('regalos', 'Regalos y Fiestas'), ('monografias', 'Monografias')], default='escolar', max_length=20),
        ),
    ]
