# Generated by Django 4.1.7 on 2023-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0004_alter_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lugar',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
