# Generated by Django 4.1.7 on 2023-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0005_producto_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='img_productos'),
        ),
    ]
