# Generated by Django 4.1.7 on 2023-03-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
