# Generated by Django 4.1.7 on 2023-03-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0008_alter_producto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
